In [1]:
import numpy as np

In [14]:
A = np.array([[2, 0], [3, 1], [4, 5]])
B = np.array([[3, 1, -1], [4, -2, 2]])
C = np.array([[2, 0], [0, 2]])

In [15]:
print(A.T)
product = np.dot(A, B)
print(product)
print(np.linalg.det(product))
print(np.linalg.inv(C))

[[2 3 4]
 [0 1 5]]
[[ 6  2 -2]
 [13  1 -1]
 [32 -6  6]]
1.144917494144693e-14
[[0.5 0. ]
 [0.  0.5]]
