In [ ]:
import numpy as np

In [3]:
v1 = np.array([2, 3, 1])
v2 = np.array([3, 4, 2])

In [4]:
print(v1 + v2)
print(2 * v1)
print(np.dot(v1, 2))
print(np.cross(v1, v2))
print(np.linalg.norm(v1))

[5 7 3]
[4 6 2]
[4 6 2]
[ 2 -1 -1]
3.7416573867739413
